export const dynamic = "force-dynamic";

import type { Metadata } from "next";
import AppProgressProvider from "../providers/progress-provider";
import { MuiLocalizationProvider } from "../providers/mui-localization-provider";
import { AppThemeProvider } from "../providers/theme-provider";
import QueryProvider from "../providers/query-provider";
import { UserProvider } from "../providers/user-provider";
import { getUser } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en">
      <body>
        <UserProvider user={user}>
          <QueryProvider>
            <MuiLocalizationProvider>
              <AppThemeProvider>
                <AppProgressProvider>{children}</AppProgressProvider>
              </AppThemeProvider>
            </MuiLocalizationProvider>
          </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
