import type { Metadata } from "next";
import AppProgressProvider from "./nprogress";
import { MuiLocalizationProvider } from "../providers/mui-localization-provider";
import { MuiThemeProvider } from "../providers/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <MuiLocalizationProvider>
          <MuiThemeProvider>
            <AppProgressProvider>{children}</AppProgressProvider>
          </MuiThemeProvider>
        </MuiLocalizationProvider>
      </body>
    </html>
  );
}
