import type { Metadata } from "next";
import AppProgressProvider from "./nprogress";
import { MuiLocalizationProvider } from "../providers/mui-localization-provider";
import { MuiThemeProvider } from "../providers/theme-provider";
import QueryProvider from "../providers/query-provider";
import { UserProvider } from "../providers/user-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <UserProvider>
          <QueryProvider>
            <MuiLocalizationProvider>
              <MuiThemeProvider>
                <AppProgressProvider>{children}</AppProgressProvider>
              </MuiThemeProvider>
            </MuiLocalizationProvider>
          </QueryProvider>
        </UserProvider>
      </body>
    </html>
  );
}
